export const API_URL = 'http://127.0.0.1:8000/';

export const INIT_STATE = {
    posts: {
        isLoading: false,
        data: [],
        list: [],
        search: [],
    },
    login: {
        isLoading: false,
        data: [],
    }
}

export const snackBarConstants = {
    INIT_STATE : {
        isOpen: false,
        severity: 'success',
        message: '',
    },
    POPUP: 'SNACKBAR_POPUP',
    INIT: 'SNACKBAR_INIT',
}

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    REFRESH_TOKEN_REQUEST: 'REFRESH_NEW_TOKEN_REQUEST',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_NEW_TOKEN_SUCCESS',
    REFRESH_TOKEN_FAILURE: 'REFRESH_NEW_TOKEN_FAILURE',

    VERIFY_TOKEN_REQUEST: 'VERIFY_CURRENT_TOKEN_REQUEST',
    VERIFY_TOKEN_SUCCESS: 'VERIFY_CURRENT_TOKEN_SUCCESS',
    VERIFY_TOKEN_FAILURE: 'VERIFY_CURRENT_TOKEN_FAILURE',

    RESET_PASS_REQUEST: 'USER_RESET_PASSWORD_REQUEST',
    RESET_PASS_SUCCESS: 'USER_RESET_PASSWORD_SUCCESS',
    RESET_PASS_FAILURE: 'USER_RESET_PASSWORD_FAILURE',

    ACCOUNT_ACTIVATE_REQUEST: 'USER_ACCOUNT_ACTIVATION_REQUEST',
    ACCOUNT_ACTIVATE_SUCCESS: 'USER_ACCOUNT_ACTIVATION_SUCCESS',
    ACCOUNT_ACTIVATE_FAILURE: 'USER_ACCOUNT_ACTIVATION_FAILURE',
};

export const imageTypes = {
    CONTENTS_IMAGE: 'contents',
    ARTICLE_HEADING: 'heading',
    AVATAR_USER: 'avatar'
}

export const language = {
    VIETNAMESE: 'vi-VN',
    ENGLISH: 'en-EN'
}

export const tagConstants = {
    GET_LIST_REQUEST: 'GET_LIST_TAG_REQUEST',
    GET_LIST_FAILURE: 'GET_LIST_TAG_FAILURE',
    GET_LIST_SUCCESS: 'GET_LIST_TAG_SUCCESS',

    GET_DETAIL_REQUEST: 'GET_TAG_DETAIL_REQUEST',
    GET_DETAIL_SUCCESS: 'GET_TAG_DETAIL_SUCCESS',
    GET_DETAIL_FAILURE: 'GET_TAG_DETAIL_FAILURE',

    DEL_LIST_REQUEST: 'DEL_TAG_LIST_REQUEST',
    DEL_LIST_SUCCESS: 'DEL_TAG_LIST_SUCCESS',
    DEL_LIST_FAILURE: 'DEL_TAG_LIST_FAILURE',

    DEL_REQUEST: 'DEL_TAG_REQUEST',
    DEL_SUCCESS: 'DEL_TAG_SUCCESS',
    DEL_FAILURE: 'DEL_TAG_FAILURE',

    POST_REQUEST: 'POST_TAG_REQUEST',
    POST_SUCCESS: 'POST_TAG_SUCCESS',
    POST_FAILURE: 'POST_TAG_FAILURE',

    EDIT_REQUEST: 'PUT_TAG_REQUEST',
    EDIT_SUCCESS: 'PUT_TAG_SUCCESS',
    EDIT_FAILURE: 'PUT_TAG_FAILURE',
}

export const categoryConstants = {
    GET_LIST_REQUEST: 'GET_LIST_CATEGORY_REQUEST',
    GET_LIST_FAILURE: 'GET_LIST_CATEGORY_FAILURE',
    GET_LIST_SUCCESS: 'GET_LIST_CATEGORY_SUCCESS',

    GET_DETAIL_REQUEST: 'GET_CATEGORY_DETAIL_REQUEST',
    GET_DETAIL_SUCCESS: 'GET_CATEGORY_DETAIL_SUCCESS',
    GET_DETAIL_FAILURE: 'GET_CATEGORY_DETAIL_FAILURE',

    DEL_LIST_REQUEST: 'DEL_CATEGORY_LIST_REQUEST',
    DEL_LIST_SUCCESS: 'DEL_CATEGORY_LIST_SUCCESS',
    DEL_LIST_FAILURE: 'DEL_CATEGORY_LIST_FAILURE',

    DEL_REQUEST: 'DEL_CATEGORY_REQUEST',
    DEL_SUCCESS: 'DEL_CATEGORY_SUCCESS',
    DEL_FAILURE: 'DEL_CATEGORY_FAILURE',

    POST_REQUEST: 'POST_CATEGORY_REQUEST',
    POST_SUCCESS: 'POST_CATEGORY_SUCCESS',
    POST_FAILURE: 'POST_CATEGORY_FAILURE',

    EDIT_REQUEST: 'PUT_CATEGORY_REQUEST',
    EDIT_SUCCESS: 'PUT_CATEGORY_SUCCESS',
    EDIT_FAILURE: 'PUT_CATEGORY_FAILURE',
}

export const articleConstants = {
    GET_LIST_REQUEST: 'GET_LIST_ARTICLE_REQUEST',
    GET_LIST_FAILURE: 'GET_LIST_ARTICLE_FAILURE',
    GET_LIST_SUCCESS: 'GET_LIST_ARTICLE_SUCCESS',

    GET_DETAIL_REQUEST: 'GET_ARTICLE_DETAIL_REQUEST',
    GET_DETAIL_SUCCESS: 'GET_ARTICLE_DETAIL_SUCCESS',
    GET_DETAIL_FAILURE: 'GET_ARTICLE_DETAIL_FAILURE',

    DEL_LIST_REQUEST: 'DEL_ARTICLE_LIST_REQUEST',
    DEL_LIST_SUCCESS: 'DEL_ARTICLE_LIST_SUCCESS',
    DEL_LIST_FAILURE: 'DEL_ARTICLE_LIST_FAILURE',

    DEL_REQUEST: 'DEL_ARTICLE_REQUEST',
    DEL_SUCCESS: 'DEL_ARTICLE_SUCCESS',
    DEL_FAILURE: 'DEL_ARTICLE_FAILURE',

    POST_REQUEST: 'POST_ARTICLE_REQUEST',
    POST_SUCCESS: 'POST_ARTICLE_SUCCESS',
    POST_FAILURE: 'POST_ARTICLE_FAILURE',

    EDIT_REQUEST: 'PUT_ARTICLE_REQUEST',
    EDIT_SUCCESS: 'PUT_ARTICLE_SUCCESS',
    EDIT_FAILURE: 'PUT_ARTICLE_FAILURE',
}

export const imageConstants = {
    GET_LIST_IMG_REQUEST: 'IMAGE_GET_LIST_REQUEST',
    GET_LIST_IMG_SUCCESS: 'IMAGE_GET_LIST_SUCCESS',
    GET_LIST_IMG_FAILURE: 'IMAGE_GET_LIST_FAILURE',

    GET_IMG_REQUEST: 'IMAGE_GET_DETAIL_REQUEST',
    GET_IMG_SUCCESS: 'IMAGE_GET_DETAIL_SUCCESS',
    GET_IMG_FAILURE: 'IMAGE_GET_DETAIL_FAILURE',

    UPLOAD_IMG_REQUEST: 'IMAGE_UPLOAD_REQUEST',
    UPLOAD_IMG_SUCCESS: 'IMAGE_UPLOAD_SUCCESS',
    UPLOAD_IMG_FAILURE: 'IMAGE_UPLOAD_FAILURE',

    DEL_IMG_SUCCESS: 'IMAGE_DELETE_REQUEST',
    DEL_IMG_FAILURE: 'IMAGE_DELETE_FAILURE',
    DEL_IMG_REQUEST: 'IMAGE_DELETE_SUCCESS',

    DEL_LIST_IMG_REQUEST: 'IMAGE_LIST_DELETE_REQUEST',
    DEL_LIST_IMG_FAILURE: 'IMAGE_LIST_DELETE_FAILURE',
    DEL_LIST_IMG_SUCCESS: 'IMAGE_LIST_DELETE_SUCCESS',
}